# Generated by Django 2.1 on 2018-10-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pic2',
            field=models.ImageField(blank=True, default='default1.png', upload_to=''),
        ),
    ]
