# Generated by Django 2.1 on 2018-10-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
